INFO - 2023-09-19 04:19:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:20:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 04:20:17 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sales_system', 3306, '', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#6 C:\Users\kado\Documents\sales-system\app\Models\UserModel.php(38): CodeIgniter\BaseModel->first()
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(86): App\Models\UserModel->login_user('alkadohs', '1234')
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->login()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#5 C:\Users\kado\Documents\sales-system\app\Models\UserModel.php(38): CodeIgniter\BaseModel->first()
#6 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(86): App\Models\UserModel->login_user('alkadohs', '1234')
#7 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->login()
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#12 {main}
CRITICAL - 2023-09-19 04:20:17 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `username` = :username:
AND `password` = :password:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(662): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(38): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\User.php(86): App\Models\UserModel->login_user('alkadohs', '1234')
 7 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->login()
 8 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 04:21:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:21:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:21:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:21:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:21:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:21:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:26:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:26:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:27:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:27:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:27:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 04:27:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:01:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:02:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:14:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:14:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:14:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:18:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:27:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:28:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:28:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:33:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:42:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:42:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:48:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:48:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:48:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:50:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:51:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:52:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 05:57:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:01:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:02:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:03:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:07:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:08:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:08:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:08:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:09:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:13:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:13:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:16:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:16:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:17:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:20:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:24:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:25:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:25:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:26:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:26:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:26:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:29:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:29:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:30:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:35:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:35:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:52:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:53:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:53:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:54:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:55:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 06:59:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:01:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:01:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:05:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:06:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:06:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:07:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:08:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:09:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:10:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:12:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:15:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:15:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:17:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:19:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:20:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:27:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:41:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:41:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:42:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:55:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:56:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 07:56:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 08:03:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:29:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:30:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:30:07 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'sales_system', 3306, '', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#6 C:\Users\kado\Documents\sales-system\app\Models\UserModel.php(38): CodeIgniter\BaseModel->first()
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(86): App\Models\UserModel->login_user('alkadohs', '1234')
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->login()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#5 C:\Users\kado\Documents\sales-system\app\Models\UserModel.php(38): CodeIgniter\BaseModel->first()
#6 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(86): App\Models\UserModel->login_user('alkadohs', '1234')
#7 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->login()
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#12 {main}
CRITICAL - 2023-09-19 18:30:07 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `username` = :username:
AND `password` = :password:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(662): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(38): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\User.php(86): App\Models\UserModel->login_user('alkadohs', '1234')
 7 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->login()
 8 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:30:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:30:28 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(99): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->login()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:30:28 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(99): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->login()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:30:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:30:33 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(99): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->login()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:30:33 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(99): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->login()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:30:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:30:45 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(99): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->login()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:30:45 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(99): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->login()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:30:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:30:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:31:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:31:06 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:31:06 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:33:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:33:37 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:33:37 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:34:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:34:19 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:34:19 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:34:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:34:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:34:26 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:34:26 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:34:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:34:29 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:34:29 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:34:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:34:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:34:35 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:34:35 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:34:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:34:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:34:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:34:47 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:34:47 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:35:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:35:55 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:35:55 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:35:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:35:57 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:35:57 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:35:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:36:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:36:04 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:36:04 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
ERROR - 2023-09-19 18:44:54 --> mysqli_sql_exception: Invalid default value for 'updated_at' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\Users\kado\Documents\sales-system\app\Database\Migrations\2023-09-18-105602_UserTable.php(76): CodeIgniter\Database\Forge->createTable('user')
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(877): App\Database\Migrations\UserTable->up()
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CLI\BaseCommand.php(115): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Database\MigrateRefresh.php(85): CodeIgniter\CLI\BaseCommand->call('migrate', Array)
#11 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\MigrateRefresh->run(Array)
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate:refresh', Array)
#13 C:\Users\kado\Documents\sales-system\spark(102): CodeIgniter\CLI\Console->run()
#14 {main}
ERROR - 2023-09-19 18:46:23 --> mysqli_sql_exception: Invalid default value for 'updated_at' in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\Users\kado\Documents\sales-system\app\Database\Migrations\2023-09-18-105602_UserTable.php(76): CodeIgniter\Database\Forge->createTable('user')
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(877): App\Database\Migrations\UserTable->up()
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CLI\BaseCommand.php(115): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Database\MigrateRefresh.php(85): CodeIgniter\CLI\BaseCommand->call('migrate', Array)
#11 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\MigrateRefresh->run(Array)
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate:refresh', Array)
#13 C:\Users\kado\Documents\sales-system\spark(102): CodeIgniter\CLI\Console->run()
#14 {main}
INFO - 2023-09-19 18:47:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:47:50 --> mysqli_sql_exception: Table 'sales_system.user' doesn't exist in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:47:50 --> Table 'sales_system.user' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:48:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-19 18:48:03 --> mysqli_sql_exception: Table 'sales_system.user' doesn't exist in C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `user` S...', 0)
#1 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user` S...')
#2 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user` S...')
#3 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` S...', Array, false)
#4 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
#5 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\BaseModel.php(949): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Model.php(776): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\Users\kado\Documents\sales-system\app\Controllers\User.php(109): CodeIgniter\Model->update('1', Array)
#8 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(919): App\Controllers\User->logout()
#9 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\kado\Documents\sales-system\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\kado\Documents\sales-system\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\D...')
#13 {main}
CRITICAL - 2023-09-19 18:48:03 --> Table 'sales_system.user' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2475): CodeIgniter\Database\BaseConnection->query('UPDATE `user` SET `is_active` = :is_active:, `updated_at` = :updated_at:
WHERE `user`.`id` IN :user.id:', [...], false)
 2 SYSTEMPATH\Model.php(385): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(949): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\User.php(109): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\User->logout()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 18:48:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:48:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
                                                                                                                   INFO - 2023-09-19 18:58:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:58:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:58:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 18:58:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 19:01:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 19:03:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 19:03:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 19:05:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 19:10:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2023-09-19 19:51:22 --> CodeIgniter\Router\RouteCollection::processArrayCallableSyntax(): Return value must be of type string, array returned
in SYSTEMPATH\Router\RouteCollection.php on line 1553.
 1 SYSTEMPATH\Router\RouteCollection.php(1417): CodeIgniter\Router\RouteCollection->processArrayCallableSyntax('branch', [...])
 2 SYSTEMPATH\Router\RouteCollection.php(1013): CodeIgniter\Router\RouteCollection->create('get', 'branch', [...], null)
 3 APPPATH\Config\Routes.php(25): CodeIgniter\Router\RouteCollection->get('/', [...])
 4 SYSTEMPATH\Router\RouteCollection.php(772): CodeIgniter\Router\RouteCollection->{closure}(Object(CodeIgniter\Router\RouteCollection))
 5 APPPATH\Config\Routes.php(23): CodeIgniter\Router\RouteCollection->group('branch', Object(Closure))
 6 SYSTEMPATH\Router\RouteCollection.php(339): require('C:\\Users\\kado\\Documents\\sales-system\\app\\Config\\Routes.php')
 7 SYSTEMPATH\CodeIgniter.php(787): CodeIgniter\Router\RouteCollection->loadRoutes()
 8 SYSTEMPATH\CodeIgniter.php(442): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 9 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
CRITICAL - 2023-09-19 19:52:52 --> Call to undefined method App\Models\BranchModel::get_branchs
in SYSTEMPATH\Model.php on line 873.
 1 APPPATH\Controllers\Branch.php(15): CodeIgniter\Model->__call('get_branchs', [])
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Branch->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Branch))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\kado\\Documents\\sales-system\\public\\index.php')
INFO - 2023-09-19 20:03:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 20:11:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 20:11:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 20:11:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 20:12:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-19 20:12:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
